-- db/seed.sql - Initial Seed Data for GlowCart

-- Insert initial products
INSERT INTO products (id, name, description, category, price, image, rating, reviewsCount, stock, specs) VALUES
('1', 'GlowBoard X90', 'Experience the ultimate keystroke satisfaction with custom-lubed mechanical switches and vibrant, double-shot keycaps backed by multi-zone reactive RGB lighting.', 'Keyboards', 149.99, 'assets/neon_keyboard.jpg', 4.80, 124, 12, '{"Layout": "75% ANSI layout", "Switch Type": "Gateron Yellow (Linear)", "Battery Life": "Up to 150 hours (RGB off)", "Connectivity": "USB-C, Bluetooth 5.1, 2.4GHz Wireless"}'),
('2', 'CyberSound Pulse', 'Tune out the world with advanced Active Noise Cancelling. Features dynamic dual drivers, a customizable aura neon light ring, and breathable cooling-gel cushions.', 'Audio', 199.99, 'assets/cyber_headphones.jpg', 4.90, 89, 8, '{"Driver": "50mm Neodymium dynamic drivers", "ANC Level": "Up to -40dB Hybrid ANC", "Battery Life": "Up to 40 hours with ANC & RGB on", "Frequency Response": "10Hz - 40kHz"}'),
('3', 'Hologra Chrono', 'A premium smartwatch blending physical titanium craftsmanship with a high-definition holographic interface display. Tracks biometrics and projects key notifications.', 'Wearables', 299.99, 'assets/cyber_watch.jpg', 4.70, 56, 5, '{"Display": "1.4-inch Holographic Micro-OLED", "Sensors": "Heart rate, SpO2, Accelerometer, Gyroscope", "Casing Material": "Aerospace Grade Titanium", "Water Resistance": "5ATM (up to 50m)"}'),
('4', 'AuraRing Lamp', 'An elegant circular ambient desk lamp casting a beautiful blend of programmable sunset orange and neon cyan. Complete with sound-reactive music modes.', 'Smart Home', 89.99, 'assets/ambient_lamp.jpg', 4.60, 142, 15, '{"Height": "35 cm", "Control": "WiFi Smartphone App, Google/Alexa, Touch Bar", "Material": "Anodized Sandblasted Aluminum", "Illumination": "16 Million Colors + Tunable Warm White"}'),
('5', 'GlowBoard Mini (Pro Edition)', 'A compact 60% mechanical layout featuring a clean frosted acrylic shell that diffuses lighting beautifully across your workspace. Ideal for clean, minimal setups.', 'Keyboards', 119.99, 'assets/neon_keyboard.jpg', 4.50, 34, 20, '{"Layout": "60% ultra-compact layout", "Switch Type": "Cherry MX Red (Linear)", "Case Material": "Frosted CNC Polycarbonate", "Connectivity": "Detachable USB-C"}'),
('6', 'CyberSound In-Ear Buds', 'Ultra-low latency wireless earbuds engineered for gaming and music. Comes in a futuristic slide-to-open charging case with pulsing neon battery indicator stripes.', 'Audio', 79.99, 'assets/cyber_headphones.jpg', 4.40, 78, 25, '{"Latency": "38ms Ultra-Low Latency Mode", "Total Playtime": "24 hours with case", "Charging Case": "300mAh with USB-C Fast Charge", "Waterproofing": "IPX5 Sweat resistance"}'),
('7', 'Hologra Chrono Elite', 'The ultimate edition smartwatch featuring custom carbon fiber accents and a stealth-matte finish. Comes with custom watch faces and premium black steel link band.', 'Wearables', 399.99, 'assets/cyber_watch.jpg', 4.90, 18, 3, '{"Battery": "Up to 7 days smart mode / 30 days low power", "Storage": "32GB On-board audio & map storage", "Casing Material": "DLC (Diamond-Like Carbon) Coated Steel", "Strap": "Interchangeable Matte Black Stainless Link + Fluororubber Sport"}'),
('8', 'AuraSphere Glow', 'A floating-orb ambient light utilizing magnetic levitation to spin gently. Features wire-free induction charging and interactive touch colors.', 'Smart Home', 129.99, 'assets/ambient_lamp.jpg', 4.80, 22, 4, '{"Diameter": "15 cm sphere", "Technology": "Magnetic Levitation, Inductive Charging", "Base Material": "Walnut wood veneer finish", "Modes": "Breathing, Strobe, Solid, Sound-Reactive"}');

-- Insert initial users (credentials match previous frontend mock accounts)
INSERT INTO users (email, password, role, name) VALUES
('admin@glowcart.com', 'admin123', 'admin', 'Store Admin'),
('user@glowcart.com', 'user123', 'user', 'Jane Doe');
