-- db/seed.sql - Initial Seed Data for GlowCart

-- Insert initial products (Prices in Indian Rupees ₹)
INSERT INTO products (id, name, description, category, price, image, rating, reviewsCount, stock, specs) VALUES
-- Keyboards
('1', 'GlowBoard X90 RGB', 'Experience the ultimate keystroke satisfaction with custom-lubed mechanical switches and vibrant, double-shot keycaps backed by multi-zone reactive RGB lighting.', 'Keyboards', 12499, 'assets/keyboard_rgb.jpg', 4.80, 124, 12, '{"Layout": "75% ANSI layout", "Switch Type": "Gateron Yellow (Linear)", "Battery Life": "Up to 150 hours (RGB off)", "Connectivity": "USB-C, Bluetooth 5.1, 2.4GHz Wireless"}'),
('5', 'GlowBoard Mini 60% Pro', 'A compact 60% mechanical layout featuring a clean frosted acrylic shell that diffuses lighting beautifully across your workspace. Ideal for clean, minimal setups.', 'Keyboards', 9999, 'assets/keyboard_compact.jpg', 4.50, 34, 20, '{"Layout": "60% ultra-compact layout", "Switch Type": "Cherry MX Red (Linear)", "Case Material": "Frosted CNC Polycarbonate", "Connectivity": "Detachable USB-C"}'),
('25', 'GlowBoard Mechanical Pro', 'Professional-grade mechanical keyboard with hotswap switches and programmable macros for ultimate customization and performance.', 'Keyboards', 8499, 'assets/keyboard_mechanical.jpg', 4.70, 45, 15, '{"Layout": "Full-size 104 keys", "Switch Type": "Hotswap Compatible", "Material": "Aluminum Alloy Body", "Features": "Macro Keys, Per-key RGB"}'),

-- Audio
('2', 'CyberSound Pulse Headphones', 'Tune out the world with advanced Active Noise Cancelling. Features dynamic dual drivers, a customizable aura neon light ring, and breathable cooling-gel cushions.', 'Audio', 16599, 'assets/headphones_premium.jpg', 4.90, 89, 8, '{"Driver": "50mm Neodymium dynamic drivers", "ANC Level": "Up to -40dB Hybrid ANC", "Battery Life": "Up to 40 hours with ANC & RGB on", "Frequency Response": "10Hz - 40kHz"}'),
('6', 'CyberSound In-Ear Gaming Buds', 'Ultra-low latency wireless earbuds engineered for gaming and music. Comes in a futuristic slide-to-open charging case with pulsing neon battery indicator stripes.', 'Audio', 6649, 'assets/earbuds_gaming.jpg', 4.40, 78, 25, '{"Latency": "38ms Ultra-Low Latency Mode", "Total Playtime": "24 hours with case", "Charging Case": "300mAh with USB-C Fast Charge", "Waterproofing": "IPX5 Sweat resistance"}'),
('26', 'SonicWave Studio Pro', 'Studio-grade wireless headphones with exceptional sound quality, noise isolation, and extended battery life for professional audio work.', 'Audio', 19999, 'assets/headphones_studio.jpg', 4.85, 156, 10, '{"Driver": "60mm Neodymium drivers", "Impedance": "32 Ohms", "Battery": "Up to 50 hours", "Features": "Foldable design, Detachable cable"}'),
('27', 'TurboSound Gaming Buds', 'Gaming-focused earbuds with ultra-fast connectivity and immersive surround sound for competitive advantage.', 'Audio', 4999, 'assets/earbuds_compact.jpg', 4.55, 92, 18, '{"Latency": "25ms", "Drivers": "10mm Dynamic", "Colors": "RGB Lighting", "Water Resistance": "IPX4"}'),

-- Wearables/Smartwatches
('3', 'Hologra Chrono Smartwatch', 'A premium smartwatch blending physical titanium craftsmanship with a high-definition holographic interface display. Tracks biometrics and projects key notifications.', 'Wearables', 24999, 'assets/watch_holographic.jpg', 4.70, 56, 5, '{"Display": "1.4-inch Holographic Micro-OLED", "Sensors": "Heart rate, SpO2, Accelerometer, Gyroscope", "Casing Material": "Aerospace Grade Titanium", "Water Resistance": "5ATM (up to 50m)"}'),
('7', 'Hologra Chrono Elite', 'The ultimate edition smartwatch featuring custom carbon fiber accents and a stealth-matte finish. Comes with custom watch faces and premium black steel link band.', 'Wearables', 33249, 'assets/watch_elite.jpg', 4.90, 18, 3, '{"Battery": "Up to 7 days smart mode / 30 days low power", "Storage": "32GB On-board audio & map storage", "Casing Material": "DLC (Diamond-Like Carbon) Coated Steel", "Strap": "Interchangeable Matte Black Stainless Link + Fluororubber Sport"}'),
('28', 'FitWear Band Pro', 'Advanced fitness tracking band with real-time health monitoring, sleep analysis, and personalized workout recommendations.', 'Wearables', 5499, 'assets/watch_fitness.jpg', 4.65, 203, 22, '{"Sensors": "Heart rate, Blood oxygen, Sleep tracking", "Battery": "14 days", "Display": "1.1-inch AMOLED", "Water Resistant": "50m"}'),

-- Mobiles
('29', 'CyberPhone Pro Max', 'Premium flagship smartphone with cutting-edge processor, stunning display, and professional-grade camera system for content creators.', 'Mobiles', 79999, 'assets/phone_premium.jpg', 4.88, 342, 8, '{"Processor": "Latest 3nm chip", "Display": "6.7-inch 120Hz AMOLED", "Camera": "200MP Main + 50MP Ultra-wide", "Battery": "5000mAh with 65W charging"}'),
('30', 'NexusMobile Ultra', 'Ultra-slim gaming phone with vapor cooling and 165Hz display for the ultimate gaming experience.', 'Mobiles', 64999, 'assets/phone_gaming.jpg', 4.92, 289, 12, '{"Processor": "Flagship Gaming Chip", "Display": "6.8-inch 165Hz LTPO", "RAM": "16GB LPDDR5X", "Storage": "512GB UFS 4.0"}'),
('31', 'MinimalPhone X', 'Sleek and elegant mid-range phone with excellent performance, long battery life, and minimal bloatware for everyday users.', 'Mobiles', 34999, 'assets/phone_minimal.jpg', 4.55, 567, 20, '{"Processor": "Mid-range flagship", "Display": "6.5-inch 90Hz", "Camera": "108MP Main + 16MP Ultra-wide", "Battery": "4500mAh"}'),

-- Laptops
('32', 'CodeMaster Pro 16', 'High-performance laptop designed for developers with powerful processor, excellent cooling, and stunning 16-inch display.', 'Laptops', 149999, 'assets/laptop_developer.jpg', 4.85, 234, 6, '{"Processor": "Latest i9 / M3 Max", "RAM": "32GB LPDDR5", "Storage": "1TB SSD", "Display": "16-inch 2.5K 165Hz", "GPU": "RTX 4090 / GPU cluster"}'),
('33', 'UltraBook Elite', 'Ultra-slim and lightweight laptop for professionals who need performance without the weight. All-day battery life included.', 'Laptops', 119999, 'assets/laptop_ultrabook.jpg', 4.70, 178, 9, '{"Processor": "Latest i7 / M2 Pro", "RAM": "16GB Unified Memory", "Storage": "512GB SSD", "Display": "14-inch OLED 3K", "Weight": "1.2kg"}'),
('34', 'GameForce Beast', 'Ultimate gaming laptop with top-tier GPU and high refresh rate display for seamless gaming at max settings.', 'Laptops', 189999, 'assets/laptop_gaming.jpg', 4.93, 412, 5, '{"Processor": "i9 13th Gen", "GPU": "RTX 4090", "RAM": "64GB DDR5", "Display": "17.3-inch 240Hz 1440p", "Cooling": "Advanced vapor chamber"}'),
('35', 'BudgetBook Plus', 'Affordable laptop perfect for students and general users. Great battery life and reliable performance for daily tasks.', 'Laptops', 44999, 'assets/laptop_budget.jpg', 4.40, 289, 18, '{"Processor": "Ryzen 5 5500U", "RAM": "8GB DDR4", "Storage": "256GB SSD", "Display": "15.6-inch FHD 60Hz", "Battery": "Up to 10 hours"}'),

-- Gaming Accessories
('36', 'RGB Gaming Mouse Pro', 'Professional gaming mouse with precision sensor, programmable buttons, and customizable RGB lighting for competitive gaming.', 'Gaming Tools', 3999, 'assets/mouse_gaming.jpg', 4.78, 156, 25, '{"DPI": "16000 DPI", "Buttons": "8 Programmable", "Weight": "95g", "Polling Rate": "8000Hz"}'),
('37', 'ThunderPad Gaming', 'Premium gaming mousepad with hard surface for maximum speed and control during intense gaming sessions.', 'Gaming Tools', 2499, 'assets/mousepad_gaming.jpg', 4.60, 203, 35, '{"Size": "400x900mm", "Thickness": "4mm", "Base": "Non-slip rubber", "Edge": "Stitched reinforcement"}'),
('38', 'CyberChair Ergonomic', 'Ergonomic gaming chair designed for long gaming sessions with lumbar support and adjustable armrests.', 'Gaming Tools', 24999, 'assets/chair_gaming.jpg', 4.82, 89, 7, '{"Material": "High-density foam", "Recline": "180° recline", "Lumbar Support": "Adjustable", "Max Weight": "150kg"}'),
('39', 'StreamHub Pro Controller', 'Advanced gaming controller with customizable buttons, haptic feedback, and wireless connectivity for console and PC gaming.', 'Gaming Tools', 5999, 'assets/controller_gaming.jpg', 4.71, 134, 16, '{"Connectivity": "Wireless 2.4GHz + Bluetooth", "Battery": "20 hours", "Features": "Haptic feedback, Adaptive triggers", "Compatibility": "PC, Console"}'),

-- Tech Tools
('40', 'CableMesh Organizer', 'Premium cable management system for clean and organized desktop setup with magnetic cable clips.', 'Tech Tools', 1499, 'assets/cable_organizer.jpg', 4.50, 234, 40, '{"Material": "Silicone + Aluminum", "Channels": "5 clips included", "Adhesive": "Strong 3M backing", "Reusable": "Yes"}'),
('41', 'MegaPower USB Hub Pro', 'Advanced USB hub with multiple ports, fast charging, and support for high-speed data transfer up to 10Gbps.', 'Tech Tools', 3499, 'assets/usb_hub.jpg', 4.68, 145, 20, '{"USB Ports": "4x USB 3.0 + 2x USB-C", "Charging": "100W Power Delivery", "Data Speed": "10Gbps", "Aluminum chassis": "Yes"}'),
('42', 'ThermalVision Cooler', 'Laptop cooling pad with temperature sensor and automatic fan speed adjustment to keep your device cool.', 'Tech Tools', 4999, 'assets/laptop_cooler.jpg', 4.73, 178, 14, '{"Fans": "Dual 120mm", "Noise": "22dB", "Temperature Range": "5°C - 65°C", "Compatibility": "Universal 15-17 inch"}'),
('43', 'ChargeStream Dock', 'Multi-device wireless charging dock supporting phones, watches, and earbuds with fast charging technology.', 'Tech Tools', 5499, 'assets/charging_dock.jpg', 4.64, 156, 12, '{"Devices": "3 in 1 charging", "Output": "15W Wireless", "Compatibility": "All Qi devices", "Material": "Premium silicone"}'),
('44', 'ScreenShield Pro', 'Anti-glare screen protector for laptops and tablets with reduced blue light to protect your eyes during long work sessions.', 'Tech Tools', 1999, 'assets/screen_protector.jpg', 4.55, 89, 50, '{"Blue Light Filter": "90% reduction", "Glare": "Anti-reflective", "Clarity": "Crystal clear", "Easy Installation": "Yes"}');

-- Insert initial users (credentials match previous frontend mock accounts)
INSERT INTO users (email, password, role, name) VALUES
('admin@glowcart.com', 'admin123', 'admin', 'Store Admin'),
('user@glowcart.com', 'user123', 'user', 'Jane Doe');
